server.port=8080

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/cipherwatch_db
spring.datasource.username=root
spring.datasource.password=07061964
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.thread-pool.size=10
app.thread-pool.timeout-seconds=15
app.risk.alert-threshold=70
app.api.abuseipdb.key=PLACEHOLDER
app.api.virustotal.key=PLACEHOLDER
app.api.ipinfo.token=PLACEHOLDER
app.name=CipherWatch
app.version=1.0.0